### ISSUE TITLE
Not work demo.

### ISSUE THREAD

**Issue by fedorax** [jgravois/lrm-esri#5]
Currently, Demo site doesn't works. Please check  it.

**Comment by jgravois** [comment]
i don't work @Esri anymore and it looks like someone disabled the account i used to create my own proxied service.

if you want to see the plugin in action, check out the [OAuth2 demo](https://johngravois.com/lrm-esri/examples/oauth/index.html).

if you want to see the proxied service demo working, you can create your own.

https://github.com/jgravois/lrm-esri#use-a-proxied-service
