### ISSUE TITLE
Direction menu not showing

### ISSUE THREAD

**Issue by drakeerv** [jgravois/lrm-esri#6]
I am trying to get this to work and it draws the menu outline but puts nothing on it. Here is the link: [https://map.drakefletcher2.repl.co/](https://map.drakefletcher2.repl.co/)
here is the code:
[https://replit.com/@DrakeFletcher2/Map](https://replit.com/@DrakeFletcher2/Map)
Am I doing anything wrong?

**Comment by jgravois** [comment]
it looks like you aren't following the instructions in the README.
```js
L.Routing.esri({
  liveTraffic: true,
  profile: 'Driving',
  // you need either a 'url' or 'token' here
})
```
https://github.com/jgravois/lrm-esri#authentication

**Comment by drakeerv** [comment]
Ohh, that makes sense. Thanks!
