### ISSUE TITLE
 Routing error: {status: -3, message: "TypeError: Cannot read properties of undefined (reading 'features')"}

### ISSUE THREAD

**Issue by vanminh1310** [jgravois/lrm-esri#7]
I got the following error. I don't know how to solve it or help me.
![image](https://user-images.githubusercontent.com/53778428/162587385-9a38309f-0c99-4b20-b9ec-54fdd03b5eb4.png)

**Comment by jgravois** [comment]
sorry but without more info, there's nothing I can do to help you.
